name: test1
on: []
jobs:
  linux:
    container:
      image: node:latest
    runs-on: ubuntu-latest
    # steps:
    #   - name: Setup MySQL
    #     uses: mirromutth/mysql-action@v1.1
    #     with:
    #       host port: 3310
    #       container port: 3306
    #       character set server: "utf8mb4"
    #       collation server: "utf8mb4_general_ci"
    #       mysql version: 5.7
    #       mysql database: "my_database"
    #       mysql user: "user"
    #       mysql password: "password"
    steps:
      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '11'
          postgresql db: 'my_database'
          postgresql user: 'my_user'
          postgresql password: 'my_password'
      - uses: actions/checkout@v1     
      - run: npm ci
        working-directory: ./postgres
      - run: node client.js
        working-directory: ./postgres
        env:
          # use postgres for the host here because we have specified a container for the job.
          # If we were running the job on the VM this would be localhost
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
